### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Wolfos** [codemakerai/codemaker-jetbrains#3]
In Rider, this plugin does nothing. Clicking code generation or documentation generation in any context, nothing will happen. No error message or anything.

In addition, the Discord link on your website is broken.

**Comment by codemakerai-dev** [comment]
Hello,

Could you please mention which language you want to generate the code for? Currently, the list of supported programming languages is somehow limited to only 3 as stated in the documentation: https://codemakerai.gitbook.io/documentation/. We are actively working on expanding and supporting more programming languages including C#.

This Discord link should work: https://discord.gg/CAh32qBZEV

**Comment by codemakerai-dev** [comment]
We had just launched support for C# for JetBrains products: https://beta.codemaker.ai/blog. Let us know if that addresses your needs.

**Comment by codemakerai-dev** [comment]
Closing ticket. Feel free to leave any feedback.
